package: nv_defaultaddons
version: 1.0.0
author: 'novinet GmbH & Co. KG'
supportpage: 'https://github.com/novinet-git/nv_defaultaddons'
page:
    title: nvDefaultAddons
    perm: 'nv_defaultaddons[]'
    pjax: true
    subpages:
        install: { title: 'translate:install' }
        info: { title: translate:info }
requires:
    packages:
        backup: ^2.3.0
        structure/content: ^2.7.0
    redaxo: ^5.9.0

